# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: lint
        name: Linter
        entry: "scripts/lint-pre-commit.sh"
        language: python
        #        language_version: python3.9
        types: [python]
        require_serial: true
        verbose: true

  - repo: local
    hooks:
      - id: test
        name: Test
        entry: "scripts/test-pre-commit.sh"
        language: python
        #        language_version: python3.9
        types: [python]
        require_serial: true
        verbose: true

  - repo: local
    hooks:
      - id: static-analysis
        name: Static analysis
        entry: "scripts/static-pre-commit.sh"
        language: python
        #        language_version: python3.9
        types: [python]
        require_serial: true
        verbose: true

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: |
          (?x)^(
              package.lock.json|
              pnpm-lock.yaml|
          )$
