# fly.toml app configuration file generated for poi_scraper on 2024-11-06T14:23:48Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'poi-scraper-ctnkz'
primary_region = 'ams'

[build]
  dockerfile = 'docker/Dockerfile'

[http_service]
  internal_port = 8888
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
