version: '3'

services:
  python-3.11-poi_scraper:  # nosemgrep
    image: mcr.microsoft.com/devcontainers/python:3.11
    container_name: poi_scraper-${USER}-python-3.11
    volumes:
      - ../:/workspaces/poi_scraper:cached
    command: sleep infinity
    
    env_file:
      - ./devcontainer.env
    networks:
      - poi_scraper-network
  
networks:
  poi_scraper-network:
    name: poi_scraper-${USER}-network
