
name: Test

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies and library
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          pip install -e ".[lint,testing]"
      - name: Run mypy
        shell: bash
        run: mypy poi_scraper tests

      - name: Run bandit
        shell: bash
        run: bandit -c pyproject.toml -r poi_scraper

      - name: Run Semgrep
        shell: bash
        run: semgrep scan --config auto --error
  test:
    strategy:
      matrix:
        python-version: ["3.11"]
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: testing

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: pyproject.toml
      - uses: actions/cache@v4
        id: cache
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-v03
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install .[testing]
      - name: Check for OPENAI_API_KEY
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "Error: OPENAI_API_KEY is not set in GitHub secrets."
            echo "Please set the OPENAI_API_KEY secret in your repository settings."
            echo "Follow the instructions here:"
            echo "https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#creating-secrets-for-a-repository"
            exit 1
          fi
      - name: Run tests
        run: pytest
        env:
          CONTEXT: ${{ runner.os }}-py${{ matrix.python-version }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  pre-commit-check:
    runs-on: ubuntu-latest
    env:
      SKIP: "static-analysis, test"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Set $PY environment variable
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install Dependencies
        run: pip install .[dev]
      - uses: pre-commit/action@v3.0.1

